name: belajar_dart_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.7

publish_to: none
# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  belajar_dart_library:
    git: 
      url: https://github.com/epul2207/belajar_dart_library.git
      ref: 1.0.0 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
